name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Code checkout 
      uses: actions/checkout@v2

    - name: Install Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.PROJECT_ID }}  
        service_account_key: ${{ secrets.GCP_KEY }}  

    - name: Build and Push the Docker image
      env: 
        Project_id : ${{ secrets.PROJECT_ID }}
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t us-central1-docker.pkg.dev/$Project_id/demo-dev-repository-us-central1/simpython:$GITHUB_RUN_NUMBER .
        docker push us-central1-docker.pkg.dev/$Project_id/demo-dev-repository-us-central1/simpython:$GITHUB_RUN_NUMBER

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v0
      with: 
        credentials_json:  ${{ secrets.GCP_KEY }}  
    - name: Deploy to Cloud Run
      env: 
          Project_id : ${{ secrets.PROJECT_ID }}
      uses: google-github-actions/deploy-cloudrun@main
      with:
        image: us-central1-docker.pkg.dev/$Project_id/demo-dev-repository-us-central1/simpython:8
        service: simpython
        region: us-central1


    
