name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:



  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Install Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.PROJECT_ID }}  
        service_account_key: ${{ secrets.GCP_KEY }}  

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v0
      with: 
        credentials_json: ${{ secrets.GCP_KEY }}  

    - name: Deploy to Cloud Run
      env: 
        Project_id: ${{ secrets.PROJECT_ID }}
        TAG: "${{ github.run_number }}"
      uses: google-github-actions/deploy-cloudrun@main
      with:
        image: us-central1-docker.pkg.dev/$Project_id/demo-dev-repository-us-central1/simpython:latest
        service: simpython
        region: us-central1

